# Project Name
PROJECT = hyper_chord

# Project Sources
UCSRC = hyper_chord.cpp

# Library Locations
# Dit wijst naar de root van de logue-sdk (4 mappen omhoog)
CMSISDIR = ../../../../CMSIS
TOOLSDIR = ../../../../tools

# Include de standaard build rules voor NTS-1 MKII
include $(TOOLSDIR)/make/project.mk